name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
          cache: pip
          cache-dependency-path: setup.py
      - run: sudo apt-get update
      - run: ./deps.sh --yes
      - run: pip install coverage nose
      - run: python ./setup.py install
      - run: python ./setup.py test
